# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip==21.3.1
            pip install -r requirements.txt -v

      - run:
          name: Run tests
          command: |
            python -m pytest /app/test_sparse_recommender.py  # Adjust the path if needed

workflows:
  version: 2
  build:
    jobs:
      - build
