# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9 # Use an appropriate Python version

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python -m pytest test.py

workflows:
  version: 2
  build:
    jobs:
      - build
